---
name: Perl CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ['5.32', '5.34', '5.38']

    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl ${{ matrix.perl-version }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          cpanm --quiet --notest ExtUtils::MakeMaker
          cpanm --installdeps --quiet --notest . || cat $HOME/.cpanm/work/*/build.log

      - name: Run tests
        run: |
          perl Makefile.PL
          make test

      - name: Show cpanm build log on failure (Windows)
        if: runner.os == 'Windows' && failure()
        shell: pwsh
        run: Get-Content "$env:USERPROFILE\.cpanm\work\*\build.log" -Tail 100

      - name: Show cpanm build log on failure (non-Windows)
        if: runner.os != 'Windows' && failure()
        run: tail -100 "$HOME/.cpanm/work/*/build.log"
